version: "2.1"
services:
  # nginx:    
  #   restart: always
  #   # image: nginx
  #   build: ./nginx
  #   # volumes:
  #     # #~ /var/local/nginx/nginx.conf为本机目录, /etc/nginx为容器目录
  #     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     # #~ /var/local/app/dist 为本机 build 后的dist目录, /usr/src/app为容器目录,
  #     # - ./dist:/var/www/html/
  #   ports:
  #     - "8082:8082"
  #   privileged: true
  builder: 
    build: .
    ports:
        - "8083:8083"
